# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from remote.pb import service_pb2 as remote_dot_pb_dot_service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in remote/pb/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphServiceStub:
    """A result is complete only after ResultEnd AND the final RPC status OK.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Territory = channel.unary_stream(
                '/gophergraph.remote.v1.GraphService/Territory',
                request_serializer=remote_dot_pb_dot_service__pb2.TerritoryRequest.SerializeToString,
                response_deserializer=remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
                _registered_method=True)
        self.AntiTerritory = channel.unary_stream(
                '/gophergraph.remote.v1.GraphService/AntiTerritory',
                request_serializer=remote_dot_pb_dot_service__pb2.AntiTerritoryRequest.SerializeToString,
                response_deserializer=remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
                _registered_method=True)
        self.Between = channel.unary_stream(
                '/gophergraph.remote.v1.GraphService/Between',
                request_serializer=remote_dot_pb_dot_service__pb2.BetweenRequest.SerializeToString,
                response_deserializer=remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
                _registered_method=True)
        self.RunWasm = channel.unary_stream(
                '/gophergraph.remote.v1.GraphService/RunWasm',
                request_serializer=remote_dot_pb_dot_service__pb2.RunWasmRequest.SerializeToString,
                response_deserializer=remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
                _registered_method=True)
        self.ListWasmQueries = channel.unary_unary(
                '/gophergraph.remote.v1.GraphService/ListWasmQueries',
                request_serializer=remote_dot_pb_dot_service__pb2.ListWasmQueriesRequest.SerializeToString,
                response_deserializer=remote_dot_pb_dot_service__pb2.ListWasmQueriesResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/gophergraph.remote.v1.GraphService/GetServerInfo',
                request_serializer=remote_dot_pb_dot_service__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=remote_dot_pb_dot_service__pb2.ServerInfoResponse.FromString,
                _registered_method=True)


class GraphServiceServicer:
    """A result is complete only after ResultEnd AND the final RPC status OK.
    """

    def Territory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AntiTerritory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Between(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunWasm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWasmQueries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Territory': grpc.unary_stream_rpc_method_handler(
                    servicer.Territory,
                    request_deserializer=remote_dot_pb_dot_service__pb2.TerritoryRequest.FromString,
                    response_serializer=remote_dot_pb_dot_service__pb2.EncodedBatch.SerializeToString,
            ),
            'AntiTerritory': grpc.unary_stream_rpc_method_handler(
                    servicer.AntiTerritory,
                    request_deserializer=remote_dot_pb_dot_service__pb2.AntiTerritoryRequest.FromString,
                    response_serializer=remote_dot_pb_dot_service__pb2.EncodedBatch.SerializeToString,
            ),
            'Between': grpc.unary_stream_rpc_method_handler(
                    servicer.Between,
                    request_deserializer=remote_dot_pb_dot_service__pb2.BetweenRequest.FromString,
                    response_serializer=remote_dot_pb_dot_service__pb2.EncodedBatch.SerializeToString,
            ),
            'RunWasm': grpc.unary_stream_rpc_method_handler(
                    servicer.RunWasm,
                    request_deserializer=remote_dot_pb_dot_service__pb2.RunWasmRequest.FromString,
                    response_serializer=remote_dot_pb_dot_service__pb2.EncodedBatch.SerializeToString,
            ),
            'ListWasmQueries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWasmQueries,
                    request_deserializer=remote_dot_pb_dot_service__pb2.ListWasmQueriesRequest.FromString,
                    response_serializer=remote_dot_pb_dot_service__pb2.ListWasmQueriesResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=remote_dot_pb_dot_service__pb2.ServerInfoRequest.FromString,
                    response_serializer=remote_dot_pb_dot_service__pb2.ServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gophergraph.remote.v1.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gophergraph.remote.v1.GraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphService:
    """A result is complete only after ResultEnd AND the final RPC status OK.
    """

    @staticmethod
    def Territory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gophergraph.remote.v1.GraphService/Territory',
            remote_dot_pb_dot_service__pb2.TerritoryRequest.SerializeToString,
            remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AntiTerritory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gophergraph.remote.v1.GraphService/AntiTerritory',
            remote_dot_pb_dot_service__pb2.AntiTerritoryRequest.SerializeToString,
            remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Between(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gophergraph.remote.v1.GraphService/Between',
            remote_dot_pb_dot_service__pb2.BetweenRequest.SerializeToString,
            remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunWasm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gophergraph.remote.v1.GraphService/RunWasm',
            remote_dot_pb_dot_service__pb2.RunWasmRequest.SerializeToString,
            remote_dot_pb_dot_service__pb2.EncodedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWasmQueries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gophergraph.remote.v1.GraphService/ListWasmQueries',
            remote_dot_pb_dot_service__pb2.ListWasmQueriesRequest.SerializeToString,
            remote_dot_pb_dot_service__pb2.ListWasmQueriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gophergraph.remote.v1.GraphService/GetServerInfo',
            remote_dot_pb_dot_service__pb2.ServerInfoRequest.SerializeToString,
            remote_dot_pb_dot_service__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
