// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: remote/pb/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_Territory_FullMethodName       = "/gophergraph.remote.v1.GraphService/Territory"
	GraphService_AntiTerritory_FullMethodName   = "/gophergraph.remote.v1.GraphService/AntiTerritory"
	GraphService_Between_FullMethodName         = "/gophergraph.remote.v1.GraphService/Between"
	GraphService_RunWasm_FullMethodName         = "/gophergraph.remote.v1.GraphService/RunWasm"
	GraphService_ListWasmQueries_FullMethodName = "/gophergraph.remote.v1.GraphService/ListWasmQueries"
	GraphService_GetServerInfo_FullMethodName   = "/gophergraph.remote.v1.GraphService/GetServerInfo"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A result is complete only after ResultEnd AND the final RPC status OK.
type GraphServiceClient interface {
	Territory(ctx context.Context, in *TerritoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error)
	AntiTerritory(ctx context.Context, in *AntiTerritoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error)
	Between(ctx context.Context, in *BetweenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error)
	RunWasm(ctx context.Context, in *RunWasmRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error)
	ListWasmQueries(ctx context.Context, in *ListWasmQueriesRequest, opts ...grpc.CallOption) (*ListWasmQueriesResponse, error)
	GetServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) Territory(ctx context.Context, in *TerritoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[0], GraphService_Territory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerritoryRequest, EncodedBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_TerritoryClient = grpc.ServerStreamingClient[EncodedBatch]

func (c *graphServiceClient) AntiTerritory(ctx context.Context, in *AntiTerritoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[1], GraphService_AntiTerritory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AntiTerritoryRequest, EncodedBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_AntiTerritoryClient = grpc.ServerStreamingClient[EncodedBatch]

func (c *graphServiceClient) Between(ctx context.Context, in *BetweenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[2], GraphService_Between_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BetweenRequest, EncodedBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_BetweenClient = grpc.ServerStreamingClient[EncodedBatch]

func (c *graphServiceClient) RunWasm(ctx context.Context, in *RunWasmRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncodedBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[3], GraphService_RunWasm_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunWasmRequest, EncodedBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_RunWasmClient = grpc.ServerStreamingClient[EncodedBatch]

func (c *graphServiceClient) ListWasmQueries(ctx context.Context, in *ListWasmQueriesRequest, opts ...grpc.CallOption) (*ListWasmQueriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWasmQueriesResponse)
	err := c.cc.Invoke(ctx, GraphService_ListWasmQueries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, GraphService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
//
// A result is complete only after ResultEnd AND the final RPC status OK.
type GraphServiceServer interface {
	Territory(*TerritoryRequest, grpc.ServerStreamingServer[EncodedBatch]) error
	AntiTerritory(*AntiTerritoryRequest, grpc.ServerStreamingServer[EncodedBatch]) error
	Between(*BetweenRequest, grpc.ServerStreamingServer[EncodedBatch]) error
	RunWasm(*RunWasmRequest, grpc.ServerStreamingServer[EncodedBatch]) error
	ListWasmQueries(context.Context, *ListWasmQueriesRequest) (*ListWasmQueriesResponse, error)
	GetServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) Territory(*TerritoryRequest, grpc.ServerStreamingServer[EncodedBatch]) error {
	return status.Error(codes.Unimplemented, "method Territory not implemented")
}
func (UnimplementedGraphServiceServer) AntiTerritory(*AntiTerritoryRequest, grpc.ServerStreamingServer[EncodedBatch]) error {
	return status.Error(codes.Unimplemented, "method AntiTerritory not implemented")
}
func (UnimplementedGraphServiceServer) Between(*BetweenRequest, grpc.ServerStreamingServer[EncodedBatch]) error {
	return status.Error(codes.Unimplemented, "method Between not implemented")
}
func (UnimplementedGraphServiceServer) RunWasm(*RunWasmRequest, grpc.ServerStreamingServer[EncodedBatch]) error {
	return status.Error(codes.Unimplemented, "method RunWasm not implemented")
}
func (UnimplementedGraphServiceServer) ListWasmQueries(context.Context, *ListWasmQueriesRequest) (*ListWasmQueriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWasmQueries not implemented")
}
func (UnimplementedGraphServiceServer) GetServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_Territory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TerritoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).Territory(m, &grpc.GenericServerStream[TerritoryRequest, EncodedBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_TerritoryServer = grpc.ServerStreamingServer[EncodedBatch]

func _GraphService_AntiTerritory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AntiTerritoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).AntiTerritory(m, &grpc.GenericServerStream[AntiTerritoryRequest, EncodedBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_AntiTerritoryServer = grpc.ServerStreamingServer[EncodedBatch]

func _GraphService_Between_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BetweenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).Between(m, &grpc.GenericServerStream[BetweenRequest, EncodedBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_BetweenServer = grpc.ServerStreamingServer[EncodedBatch]

func _GraphService_RunWasm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunWasmRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).RunWasm(m, &grpc.GenericServerStream[RunWasmRequest, EncodedBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_RunWasmServer = grpc.ServerStreamingServer[EncodedBatch]

func _GraphService_ListWasmQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWasmQueriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).ListWasmQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_ListWasmQueries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).ListWasmQueries(ctx, req.(*ListWasmQueriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetServerInfo(ctx, req.(*ServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophergraph.remote.v1.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWasmQueries",
			Handler:    _GraphService_ListWasmQueries_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _GraphService_GetServerInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Territory",
			Handler:       _GraphService_Territory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AntiTerritory",
			Handler:       _GraphService_AntiTerritory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Between",
			Handler:       _GraphService_Between_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunWasm",
			Handler:       _GraphService_RunWasm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remote/pb/service.proto",
}
